---
# Configuration
cache:
  key: "branch-$CI_BUILD_REF_NAME"
  paths:
  - .git/modules
  - lib/runtests/env

stages:
- build
- test
- integration
- Git Sync

variables:
  OPAMYES: "true"
  OPAMROOT: "/tmp/opam-$CI_BUILD_ID"

# Jobs
build:
  stage: build
  before_script:
  - opam init -n
  - opam update -u
  - eval `opam config env`
  - make init_ci
  script:
  - make
  - ./setup_environment.sh
  except:
  - triggers
  artifacts:
    paths:
    - environment/
    expire_in: 1 day

# test_main.byte isn't yet configured to run automatically
#test:
#  stage: test
#  script:
#  - cd environment
#  - ./test_main.byte
#  except:
#  - triggers

# FIXME: Packaged JS_Parser means that we now need to distribute opam instance to condor runs
condor:
  before_script:
  - export CI_BUILD_REF_SUBJ="$(git show --pretty=format:%s -s)"
  - export TEST262_VERSION="$(git rev-parse --verify HEAD:tests/test262)"
  - git submodule update --init --force lib/runtests tests/test262
  - source lib/runtests/scripts/set-voldir.sh JavaScriptVerification
  - "# OPAM initialisation"
  - export OPAMROOT=$VOLDIR/.opam
  - opam init -n
  - opam update -u
  - eval `opam config env`
  - make init_parser
  - export OCAMLFIND_CONF=$OPAMROOT/$(opam switch show)/lib/findlib.conf
  - sed -e "s|/tmp/opam-\d+/|$OPAMROOT/|" -i $OCAMLFIND_CONF
  - "# Runtests initialisation"
  - source lib/runtests/scripts/init-env.sh
  - cp -R lib/runtests tests/test262 environment run.sh $VOLDIR
  - cd $VOLDIR
  script:
  - 'runtests/runtests.py --interp generic --interp_path ./run.sh --executor condor --batch_size 1 --condor_log --db postgres --db_pg_schema jsil --interp_version $CI_BUILD_REF --title "$CI_BUILD_REF_NAME autobuild: $CI_BUILD_REF_SUBJ" --tests_version $TEST262_VERSION --timeout 300 test262/test'
  - runtests/scripts/condor-wait.sh
  after_script:
  - lib/runtests/scripts/clean-voldir.sh JavaScriptVerification
  stage: integration
  tags:
  - condor
  except:
  - triggers


git-sync:
  stage: Git Sync
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - git sync-remote git@github.com:resource-reasoning/JavaScriptVerification.git git@gitlab.doc.ic.ac.uk:resource-reasoning/JavaScriptVerification.git
  - ssh-agent -k
  only:
  - triggers

