---
# Configuration
cache:
  key: "branch-$CI_COMMIT_REF_NAME"
  paths:
  - .git/modules
  - lib/runtests/env

stages:
- build
- test
- integration
- Git Sync

# Jobs
build:
  stage: build
  before_script:
  - make init_build
  script:
  - make
  - ./setup_environment.sh
  tags:
  - docker
  image: resourcereasoning/javascriptverification:build
  except:
  - triggers
  artifacts:
    paths:
    - environment/
    expire_in: 1 day

#single_machine:
#  before_script:
#  - export CI_BUILD_REF_SUBJ="$(git show --pretty=format:%s -s)"
#  - export TEST262_VERSION="$(git rev-parse --verify HEAD:tests/test262)"
#  - git submodule update --init --force lib/runtests tests/test262
#  - make init_parser
#  - source lib/runtests/scripts/init-env.sh
#  script:
#  - cd environment
#  - '../lib/runtests/runtests.py --interp generic --interp_path ./jsil.sh --executor sequential --interp_version $CI_COMMIT_SHA --title "$CI_COMMIT_REF_NAME autobuild: $CI_BUILD_REF_SUBJ" --tests_version $TEST262_VERSION --timeout 300 ../tests/test262/test'
#  #- 'runtests/runtests.py --interp generic --interp_path ./run.sh --executor sequential --db postgres --db_pg_schema jsil --interp_version $CI_COMMIT_SHA --title "$CI_COMMIT_REF_NAME autobuild: $CI_BUILD_REF_SUBJ" --tests_version $TEST262_VERSION --timeout 300 test262/test'
#  stage: integration
#  image: resourcereasoning/javascriptverification:build
#  tags:
#  - docker
#  except:
#  - triggers

condor:
  before_script:
  - export CI_BUILD_REF_SUBJ="$(git show --pretty=format:%s -s)"
  - export TEST262_VERSION="$(git rev-parse --verify HEAD:tests/test262)"
  - git submodule update --init --force lib/runtests tests/test262
  - source lib/runtests/scripts/set-voldir.sh JavaScriptVerification
  - "# OPAM initialisation"
  - export OPAMROOT=$VOLDIR/opam
  - "test -d $OPAMROOT && opam update -u || opam init -n"
  - eval `opam config env`
  - export OCAMLFIND_CONF=$OPAMROOT/$(opam switch show)/lib/findlib.conf
  - make init_parser
  - "# Runtests initialisation"
  - source lib/runtests/scripts/init-env.sh
  - cp -R lib/runtests tests/test262 environment/* 8797.txt $VOLDIR
  - cd $VOLDIR
  script:
  - 'runtests/runtests.py --interp jsil --interp_path environment/jsil.native --executor condor --batch_size 2 --condor_log --db postgres --db_pg_schema jsil --interp_version $CI_COMMIT_SHA --title "$CI_COMMIT_REF_NAME autobuild: $CI_BUILD_REF_SUBJ" --tests_version $TEST262_VERSION --timeout 1800 @8797.txt'
  - runtests/scripts/condor-wait.sh 70
  after_script:
  - lib/runtests/scripts/clean-voldir.sh JavaScriptVerification
  stage: integration
  tags:
  - condor
  only:
  - js2jsil_definitive
  - ci-testing
  except:
  - triggers


git-sync:
  stage: Git Sync
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - git sync-remote git@github.com:resource-reasoning/JavaScriptVerification.git git@gitlab.doc.ic.ac.uk:resource-reasoning/JavaScriptVerification.git
  - ssh-agent -k
  only:
  - triggers

